// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础指标（向后兼容）
	CpuPercent      float64 `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent      float64 `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	DiskPercent     float64 `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	MemTotal        uint64  `protobuf:"varint,4,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed         uint64  `protobuf:"varint,5,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	DiskTotal       uint64  `protobuf:"varint,6,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed        uint64  `protobuf:"varint,7,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	Timestamp       int64   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hostname        string  `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NetRateIn       float64 `protobuf:"fixed64,10,opt,name=net_rate_in,json=netRateIn,proto3" json:"net_rate_in,omitempty"`
	NetRateOut      float64 `protobuf:"fixed64,11,opt,name=net_rate_out,json=netRateOut,proto3" json:"net_rate_out,omitempty"`
	DockerAvailable bool    `protobuf:"varint,12,opt,name=docker_available,json=dockerAvailable,proto3" json:"docker_available,omitempty"`
	DockerTotal     int32   `protobuf:"varint,13,opt,name=docker_total,json=dockerTotal,proto3" json:"docker_total,omitempty"`
	DockerRunning   int32   `protobuf:"varint,14,opt,name=docker_running,json=dockerRunning,proto3" json:"docker_running,omitempty"`
	DockerStopped   int32   `protobuf:"varint,15,opt,name=docker_stopped,json=dockerStopped,proto3" json:"docker_stopped,omitempty"`
	// 扩展字段（服务器详情 Tab 用）
	Os            string         `protobuf:"bytes,16,opt,name=os,proto3" json:"os,omitempty"`
	KernelVer     string         `protobuf:"bytes,17,opt,name=kernel_ver,json=kernelVer,proto3" json:"kernel_ver,omitempty"`
	UptimeSec     uint64         `protobuf:"varint,18,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	Procs         int32          `protobuf:"varint,19,opt,name=procs,proto3" json:"procs,omitempty"`
	CpuCores      int32          `protobuf:"varint,20,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuLoad1      float64        `protobuf:"fixed64,21,opt,name=cpu_load1,json=cpuLoad1,proto3" json:"cpu_load1,omitempty"`
	CpuLoad5      float64        `protobuf:"fixed64,22,opt,name=cpu_load5,json=cpuLoad5,proto3" json:"cpu_load5,omitempty"`
	CpuLoad15     float64        `protobuf:"fixed64,23,opt,name=cpu_load15,json=cpuLoad15,proto3" json:"cpu_load15,omitempty"`
	MemAvailable  uint64         `protobuf:"varint,24,opt,name=mem_available,json=memAvailable,proto3" json:"mem_available,omitempty"`
	SwapTotal     uint64         `protobuf:"varint,25,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64         `protobuf:"varint,26,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree      uint64         `protobuf:"varint,27,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	Disks         []*DiskInfo    `protobuf:"bytes,28,rep,name=disks,proto3" json:"disks,omitempty"`
	TopCpu        []*ProcessInfo `protobuf:"bytes,29,rep,name=top_cpu,json=topCpu,proto3" json:"top_cpu,omitempty"`
	TopMem        []*ProcessInfo `protobuf:"bytes,30,rep,name=top_mem,json=topMem,proto3" json:"top_mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *SystemMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemMetrics) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SystemMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemMetrics) GetNetRateIn() float64 {
	if x != nil {
		return x.NetRateIn
	}
	return 0
}

func (x *SystemMetrics) GetNetRateOut() float64 {
	if x != nil {
		return x.NetRateOut
	}
	return 0
}

func (x *SystemMetrics) GetDockerAvailable() bool {
	if x != nil {
		return x.DockerAvailable
	}
	return false
}

func (x *SystemMetrics) GetDockerTotal() int32 {
	if x != nil {
		return x.DockerTotal
	}
	return 0
}

func (x *SystemMetrics) GetDockerRunning() int32 {
	if x != nil {
		return x.DockerRunning
	}
	return 0
}

func (x *SystemMetrics) GetDockerStopped() int32 {
	if x != nil {
		return x.DockerStopped
	}
	return 0
}

func (x *SystemMetrics) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemMetrics) GetKernelVer() string {
	if x != nil {
		return x.KernelVer
	}
	return ""
}

func (x *SystemMetrics) GetUptimeSec() uint64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

func (x *SystemMetrics) GetProcs() int32 {
	if x != nil {
		return x.Procs
	}
	return 0
}

func (x *SystemMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemMetrics) GetCpuLoad1() float64 {
	if x != nil {
		return x.CpuLoad1
	}
	return 0
}

func (x *SystemMetrics) GetCpuLoad5() float64 {
	if x != nil {
		return x.CpuLoad5
	}
	return 0
}

func (x *SystemMetrics) GetCpuLoad15() float64 {
	if x != nil {
		return x.CpuLoad15
	}
	return 0
}

func (x *SystemMetrics) GetMemAvailable() uint64 {
	if x != nil {
		return x.MemAvailable
	}
	return 0
}

func (x *SystemMetrics) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *SystemMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *SystemMetrics) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *SystemMetrics) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemMetrics) GetTopCpu() []*ProcessInfo {
	if x != nil {
		return x.TopCpu
	}
	return nil
}

func (x *SystemMetrics) GetTopMem() []*ProcessInfo {
	if x != nil {
		return x.TopMem
	}
	return nil
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fstype        string                 `protobuf:"bytes,2,opt,name=fstype,proto3" json:"fstype,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,6,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *DiskInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskInfo) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *DiskInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskInfo) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskInfo) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,4,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	RssBytes      uint64                 `protobuf:"varint,5,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

type SystemHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,3,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemHistoryEntry) Reset() {
	*x = SystemHistoryEntry{}
	mi := &file_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHistoryEntry) ProtoMessage() {}

func (x *SystemHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHistoryEntry.ProtoReflect.Descriptor instead.
func (*SystemHistoryEntry) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *SystemHistoryEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemHistoryEntry) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemHistoryEntry) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

type DockerListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Containers    []*DockerContainer     `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerListResult) Reset() {
	*x = DockerListResult{}
	mi := &file_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerListResult) ProtoMessage() {}

func (x *DockerListResult) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerListResult.ProtoReflect.Descriptor instead.
func (*DockerListResult) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *DockerListResult) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *DockerListResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DockerListResult) GetContainers() []*DockerContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

type DockerContainer struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image        string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State        string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CpuPercent   float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent   float64                `protobuf:"fixed64,6,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemUsage     uint64                 `protobuf:"varint,7,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	MemLimit     uint64                 `protobuf:"varint,8,opt,name=mem_limit,json=memLimit,proto3" json:"mem_limit,omitempty"`
	Timestamp    int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NetRxRate    float64                `protobuf:"fixed64,10,opt,name=net_rx_rate,json=netRxRate,proto3" json:"net_rx_rate,omitempty"`
	NetTxRate    float64                `protobuf:"fixed64,11,opt,name=net_tx_rate,json=netTxRate,proto3" json:"net_tx_rate,omitempty"`
	BlkReadRate  float64                `protobuf:"fixed64,12,opt,name=blk_read_rate,json=blkReadRate,proto3" json:"blk_read_rate,omitempty"`
	BlkWriteRate float64                `protobuf:"fixed64,13,opt,name=blk_write_rate,json=blkWriteRate,proto3" json:"blk_write_rate,omitempty"`
	// 详情字段
	Status       string `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Health       string `protobuf:"bytes,15,opt,name=health,proto3" json:"health,omitempty"`
	StartedAt    int64  `protobuf:"varint,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	RestartCount int32  `protobuf:"varint,17,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	PidsCurrent  uint64 `protobuf:"varint,18,opt,name=pids_current,json=pidsCurrent,proto3" json:"pids_current,omitempty"`
	// 容器详情字段（列表页可空）
	Env               []string                       `protobuf:"bytes,19,rep,name=env,proto3" json:"env,omitempty"`
	Mounts            []*DockerMount                 `protobuf:"bytes,20,rep,name=mounts,proto3" json:"mounts,omitempty"`
	PortBindings      map[string]*DockerPortBindings `protobuf:"bytes,21,rep,name=port_bindings,json=portBindings,proto3" json:"port_bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NetworkInterfaces []*DockerNetworkInterface      `protobuf:"bytes,22,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DockerContainer) Reset() {
	*x = DockerContainer{}
	mi := &file_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerContainer) ProtoMessage() {}

func (x *DockerContainer) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerContainer.ProtoReflect.Descriptor instead.
func (*DockerContainer) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *DockerContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DockerContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DockerContainer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DockerContainer) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *DockerContainer) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *DockerContainer) GetMemUsage() uint64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *DockerContainer) GetMemLimit() uint64 {
	if x != nil {
		return x.MemLimit
	}
	return 0
}

func (x *DockerContainer) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DockerContainer) GetNetRxRate() float64 {
	if x != nil {
		return x.NetRxRate
	}
	return 0
}

func (x *DockerContainer) GetNetTxRate() float64 {
	if x != nil {
		return x.NetTxRate
	}
	return 0
}

func (x *DockerContainer) GetBlkReadRate() float64 {
	if x != nil {
		return x.BlkReadRate
	}
	return 0
}

func (x *DockerContainer) GetBlkWriteRate() float64 {
	if x != nil {
		return x.BlkWriteRate
	}
	return 0
}

func (x *DockerContainer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DockerContainer) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *DockerContainer) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *DockerContainer) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *DockerContainer) GetPidsCurrent() uint64 {
	if x != nil {
		return x.PidsCurrent
	}
	return 0
}

func (x *DockerContainer) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DockerContainer) GetMounts() []*DockerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *DockerContainer) GetPortBindings() map[string]*DockerPortBindings {
	if x != nil {
		return x.PortBindings
	}
	return nil
}

func (x *DockerContainer) GetNetworkInterfaces() []*DockerNetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type DockerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Rw            bool                   `protobuf:"varint,4,opt,name=rw,proto3" json:"rw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerMount) Reset() {
	*x = DockerMount{}
	mi := &file_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerMount) ProtoMessage() {}

func (x *DockerMount) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerMount.ProtoReflect.Descriptor instead.
func (*DockerMount) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *DockerMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DockerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DockerMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DockerMount) GetRw() bool {
	if x != nil {
		return x.Rw
	}
	return false
}

type DockerPortBindings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []string               `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerPortBindings) Reset() {
	*x = DockerPortBindings{}
	mi := &file_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerPortBindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerPortBindings) ProtoMessage() {}

func (x *DockerPortBindings) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerPortBindings.ProtoReflect.Descriptor instead.
func (*DockerPortBindings) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *DockerPortBindings) GetHost() []string {
	if x != nil {
		return x.Host
	}
	return nil
}

type DockerNetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerNetworkInterface) Reset() {
	*x = DockerNetworkInterface{}
	mi := &file_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerNetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerNetworkInterface) ProtoMessage() {}

func (x *DockerNetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerNetworkInterface.ProtoReflect.Descriptor instead.
func (*DockerNetworkInterface) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *DockerNetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerNetworkInterface) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DockerNetworkInterface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *DockerNetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	OsName        string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,7,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HeartbeatSec  int32                  `protobuf:"varint,2,opt,name=heartbeat_sec,json=heartbeatSec,proto3" json:"heartbeat_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatSec() int32 {
	if x != nil {
		return x.HeartbeatSec
	}
	return 0
}

type ErrorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReport) Reset() {
	*x = ErrorReport{}
	mi := &file_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReport) ProtoMessage() {}

func (x *ErrorReport) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReport.ProtoReflect.Descriptor instead.
func (*ErrorReport) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorReport) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ErrorReport) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ErrorReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ErrorReport) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ErrorReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReportResponse) Reset() {
	*x = ErrorReportResponse{}
	mi := &file_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReportResponse) ProtoMessage() {}

func (x *ErrorReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReportResponse.ProtoReflect.Descriptor instead.
func (*ErrorReportResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{12}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{13}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_monitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetSystemMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsRequest) Reset() {
	*x = GetSystemMetricsRequest{}
	mi := &file_monitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsRequest) ProtoMessage() {}

func (x *GetSystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{15}
}

type GetSystemMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *SystemMetrics         `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsResponse) Reset() {
	*x = GetSystemMetricsResponse{}
	mi := &file_monitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsResponse) ProtoMessage() {}

func (x *GetSystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{16}
}

func (x *GetSystemMetricsResponse) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetSystemHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemHistoryRequest) Reset() {
	*x = GetSystemHistoryRequest{}
	mi := &file_monitor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemHistoryRequest) ProtoMessage() {}

func (x *GetSystemHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSystemHistoryRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{17}
}

func (x *GetSystemHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSystemHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SystemHistoryEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemHistoryResponse) Reset() {
	*x = GetSystemHistoryResponse{}
	mi := &file_monitor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemHistoryResponse) ProtoMessage() {}

func (x *GetSystemHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSystemHistoryResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{18}
}

func (x *GetSystemHistoryResponse) GetEntries() []*SystemHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetDockerMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerMetricsRequest) Reset() {
	*x = GetDockerMetricsRequest{}
	mi := &file_monitor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerMetricsRequest) ProtoMessage() {}

func (x *GetDockerMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDockerMetricsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{19}
}

type GetDockerMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*DockerContainer     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerMetricsResponse) Reset() {
	*x = GetDockerMetricsResponse{}
	mi := &file_monitor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerMetricsResponse) ProtoMessage() {}

func (x *GetDockerMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetDockerMetricsResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{20}
}

func (x *GetDockerMetricsResponse) GetContainers() []*DockerContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

type GetDockerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerListRequest) Reset() {
	*x = GetDockerListRequest{}
	mi := &file_monitor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerListRequest) ProtoMessage() {}

func (x *GetDockerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerListRequest.ProtoReflect.Descriptor instead.
func (*GetDockerListRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{21}
}

type GetDockerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *DockerListResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerListResponse) Reset() {
	*x = GetDockerListResponse{}
	mi := &file_monitor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerListResponse) ProtoMessage() {}

func (x *GetDockerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerListResponse.ProtoReflect.Descriptor instead.
func (*GetDockerListResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{22}
}

func (x *GetDockerListResponse) GetResult() *DockerListResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetDockerContainerDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerContainerDetailRequest) Reset() {
	*x = GetDockerContainerDetailRequest{}
	mi := &file_monitor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerContainerDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerContainerDetailRequest) ProtoMessage() {}

func (x *GetDockerContainerDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerContainerDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDockerContainerDetailRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{23}
}

func (x *GetDockerContainerDetailRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetDockerContainerDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *DockerContainer       `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerContainerDetailResponse) Reset() {
	*x = GetDockerContainerDetailResponse{}
	mi := &file_monitor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerContainerDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerContainerDetailResponse) ProtoMessage() {}

func (x *GetDockerContainerDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerContainerDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDockerContainerDetailResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{24}
}

func (x *GetDockerContainerDetailResponse) GetContainer() *DockerContainer {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *GetDockerContainerDetailResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

var File_monitor_proto protoreflect.FileDescriptor

const file_monitor_proto_rawDesc = "" +
	"\n" +
	"\rmonitor.proto\x12\amonitor\"\xdf\a\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\x12\x1b\n" +
	"\tmem_total\x18\x04 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x05 \x01(\x04R\amemUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x06 \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\a \x01(\x04R\bdiskUsed\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\x12\x1e\n" +
	"\vnet_rate_in\x18\n" +
	" \x01(\x01R\tnetRateIn\x12 \n" +
	"\fnet_rate_out\x18\v \x01(\x01R\n" +
	"netRateOut\x12)\n" +
	"\x10docker_available\x18\f \x01(\bR\x0fdockerAvailable\x12!\n" +
	"\fdocker_total\x18\r \x01(\x05R\vdockerTotal\x12%\n" +
	"\x0edocker_running\x18\x0e \x01(\x05R\rdockerRunning\x12%\n" +
	"\x0edocker_stopped\x18\x0f \x01(\x05R\rdockerStopped\x12\x0e\n" +
	"\x02os\x18\x10 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"kernel_ver\x18\x11 \x01(\tR\tkernelVer\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x12 \x01(\x04R\tuptimeSec\x12\x14\n" +
	"\x05procs\x18\x13 \x01(\x05R\x05procs\x12\x1b\n" +
	"\tcpu_cores\x18\x14 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tcpu_load1\x18\x15 \x01(\x01R\bcpuLoad1\x12\x1b\n" +
	"\tcpu_load5\x18\x16 \x01(\x01R\bcpuLoad5\x12\x1d\n" +
	"\n" +
	"cpu_load15\x18\x17 \x01(\x01R\tcpuLoad15\x12#\n" +
	"\rmem_available\x18\x18 \x01(\x04R\fmemAvailable\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x19 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\x1a \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\x1b \x01(\x04R\bswapFree\x12'\n" +
	"\x05disks\x18\x1c \x03(\v2\x11.monitor.DiskInfoR\x05disks\x12-\n" +
	"\atop_cpu\x18\x1d \x03(\v2\x14.monitor.ProcessInfoR\x06topCpu\x12-\n" +
	"\atop_mem\x18\x1e \x03(\v2\x14.monitor.ProcessInfoR\x06topMem\"\xb8\x01\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06fstype\x18\x02 \x01(\tR\x06fstype\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\x12!\n" +
	"\fused_percent\x18\x06 \x01(\x01R\vusedPercent\"\x92\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x04 \x01(\x01R\n" +
	"memPercent\x12\x1b\n" +
	"\trss_bytes\x18\x05 \x01(\x04R\brssBytes\"t\n" +
	"\x12SystemHistoryEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x03 \x01(\x01R\n" +
	"memPercent\"\x84\x01\n" +
	"\x10DockerListResult\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x18.monitor.DockerContainerR\n" +
	"containers\"\xdb\x06\n" +
	"\x0fDockerContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x06 \x01(\x01R\n" +
	"memPercent\x12\x1b\n" +
	"\tmem_usage\x18\a \x01(\x04R\bmemUsage\x12\x1b\n" +
	"\tmem_limit\x18\b \x01(\x04R\bmemLimit\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\vnet_rx_rate\x18\n" +
	" \x01(\x01R\tnetRxRate\x12\x1e\n" +
	"\vnet_tx_rate\x18\v \x01(\x01R\tnetTxRate\x12\"\n" +
	"\rblk_read_rate\x18\f \x01(\x01R\vblkReadRate\x12$\n" +
	"\x0eblk_write_rate\x18\r \x01(\x01R\fblkWriteRate\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\x0f \x01(\tR\x06health\x12\x1d\n" +
	"\n" +
	"started_at\x18\x10 \x01(\x03R\tstartedAt\x12#\n" +
	"\rrestart_count\x18\x11 \x01(\x05R\frestartCount\x12!\n" +
	"\fpids_current\x18\x12 \x01(\x04R\vpidsCurrent\x12\x10\n" +
	"\x03env\x18\x13 \x03(\tR\x03env\x12,\n" +
	"\x06mounts\x18\x14 \x03(\v2\x14.monitor.DockerMountR\x06mounts\x12O\n" +
	"\rport_bindings\x18\x15 \x03(\v2*.monitor.DockerContainer.PortBindingsEntryR\fportBindings\x12N\n" +
	"\x12network_interfaces\x18\x16 \x03(\v2\x1f.monitor.DockerNetworkInterfaceR\x11networkInterfaces\x1a\\\n" +
	"\x11PortBindingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.monitor.DockerPortBindingsR\x05value:\x028\x01\"k\n" +
	"\vDockerMount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x0e\n" +
	"\x02rw\x18\x04 \x01(\bR\x02rw\"(\n" +
	"\x12DockerPortBindings\x12\x12\n" +
	"\x04host\x18\x01 \x03(\tR\x04host\"\x86\x01\n" +
	"\x16DockerNetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\"\xbf\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tgrpc_port\x18\a \x01(\x05R\bgrpcPort\"G\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rheartbeat_sec\x18\x02 \x01(\x05R\fheartbeatSec\"\x9c\x01\n" +
	"\vErrorReport\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"\x15\n" +
	"\x13ErrorReportResponse\"\x14\n" +
	"\x12HealthCheckRequest\"g\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x19\n" +
	"\x17GetSystemMetricsRequest\"L\n" +
	"\x18GetSystemMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.monitor.SystemMetricsR\ametrics\"/\n" +
	"\x17GetSystemHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"Q\n" +
	"\x18GetSystemHistoryResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.monitor.SystemHistoryEntryR\aentries\"\x19\n" +
	"\x17GetDockerMetricsRequest\"T\n" +
	"\x18GetDockerMetricsResponse\x128\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x18.monitor.DockerContainerR\n" +
	"containers\"\x16\n" +
	"\x14GetDockerListRequest\"J\n" +
	"\x15GetDockerListResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.monitor.DockerListResultR\x06result\"D\n" +
	"\x1fGetDockerContainerDetailRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"w\n" +
	" GetDockerContainerDetailResponse\x126\n" +
	"\tcontainer\x18\x01 \x01(\v2\x18.monitor.DockerContainerR\tcontainer\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound2\x92\x01\n" +
	"\fAdminService\x12?\n" +
	"\bRegister\x12\x18.monitor.RegisterRequest\x1a\x19.monitor.RegisterResponse\x12A\n" +
	"\vReportError\x12\x14.monitor.ErrorReport\x1a\x1c.monitor.ErrorReportResponse2\xa5\x04\n" +
	"\rServerService\x12H\n" +
	"\vHealthCheck\x12\x1b.monitor.HealthCheckRequest\x1a\x1c.monitor.HealthCheckResponse\x12W\n" +
	"\x10GetSystemMetrics\x12 .monitor.GetSystemMetricsRequest\x1a!.monitor.GetSystemMetricsResponse\x12W\n" +
	"\x10GetSystemHistory\x12 .monitor.GetSystemHistoryRequest\x1a!.monitor.GetSystemHistoryResponse\x12W\n" +
	"\x10GetDockerMetrics\x12 .monitor.GetDockerMetricsRequest\x1a!.monitor.GetDockerMetricsResponse\x12N\n" +
	"\rGetDockerList\x12\x1d.monitor.GetDockerListRequest\x1a\x1e.monitor.GetDockerListResponse\x12o\n" +
	"\x18GetDockerContainerDetail\x12(.monitor.GetDockerContainerDetailRequest\x1a).monitor.GetDockerContainerDetailResponseB-Z+server_monitor_service/internal/protocol/pbb\x06proto3"

var (
	file_monitor_proto_rawDescOnce sync.Once
	file_monitor_proto_rawDescData []byte
)

func file_monitor_proto_rawDescGZIP() []byte {
	file_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)))
	})
	return file_monitor_proto_rawDescData
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_monitor_proto_goTypes = []any{
	(*SystemMetrics)(nil),                    // 0: monitor.SystemMetrics
	(*DiskInfo)(nil),                         // 1: monitor.DiskInfo
	(*ProcessInfo)(nil),                      // 2: monitor.ProcessInfo
	(*SystemHistoryEntry)(nil),               // 3: monitor.SystemHistoryEntry
	(*DockerListResult)(nil),                 // 4: monitor.DockerListResult
	(*DockerContainer)(nil),                  // 5: monitor.DockerContainer
	(*DockerMount)(nil),                      // 6: monitor.DockerMount
	(*DockerPortBindings)(nil),               // 7: monitor.DockerPortBindings
	(*DockerNetworkInterface)(nil),           // 8: monitor.DockerNetworkInterface
	(*RegisterRequest)(nil),                  // 9: monitor.RegisterRequest
	(*RegisterResponse)(nil),                 // 10: monitor.RegisterResponse
	(*ErrorReport)(nil),                      // 11: monitor.ErrorReport
	(*ErrorReportResponse)(nil),              // 12: monitor.ErrorReportResponse
	(*HealthCheckRequest)(nil),               // 13: monitor.HealthCheckRequest
	(*HealthCheckResponse)(nil),              // 14: monitor.HealthCheckResponse
	(*GetSystemMetricsRequest)(nil),          // 15: monitor.GetSystemMetricsRequest
	(*GetSystemMetricsResponse)(nil),         // 16: monitor.GetSystemMetricsResponse
	(*GetSystemHistoryRequest)(nil),          // 17: monitor.GetSystemHistoryRequest
	(*GetSystemHistoryResponse)(nil),         // 18: monitor.GetSystemHistoryResponse
	(*GetDockerMetricsRequest)(nil),          // 19: monitor.GetDockerMetricsRequest
	(*GetDockerMetricsResponse)(nil),         // 20: monitor.GetDockerMetricsResponse
	(*GetDockerListRequest)(nil),             // 21: monitor.GetDockerListRequest
	(*GetDockerListResponse)(nil),            // 22: monitor.GetDockerListResponse
	(*GetDockerContainerDetailRequest)(nil),  // 23: monitor.GetDockerContainerDetailRequest
	(*GetDockerContainerDetailResponse)(nil), // 24: monitor.GetDockerContainerDetailResponse
	nil,                                      // 25: monitor.DockerContainer.PortBindingsEntry
}
var file_monitor_proto_depIdxs = []int32{
	1,  // 0: monitor.SystemMetrics.disks:type_name -> monitor.DiskInfo
	2,  // 1: monitor.SystemMetrics.top_cpu:type_name -> monitor.ProcessInfo
	2,  // 2: monitor.SystemMetrics.top_mem:type_name -> monitor.ProcessInfo
	5,  // 3: monitor.DockerListResult.containers:type_name -> monitor.DockerContainer
	6,  // 4: monitor.DockerContainer.mounts:type_name -> monitor.DockerMount
	25, // 5: monitor.DockerContainer.port_bindings:type_name -> monitor.DockerContainer.PortBindingsEntry
	8,  // 6: monitor.DockerContainer.network_interfaces:type_name -> monitor.DockerNetworkInterface
	0,  // 7: monitor.GetSystemMetricsResponse.metrics:type_name -> monitor.SystemMetrics
	3,  // 8: monitor.GetSystemHistoryResponse.entries:type_name -> monitor.SystemHistoryEntry
	5,  // 9: monitor.GetDockerMetricsResponse.containers:type_name -> monitor.DockerContainer
	4,  // 10: monitor.GetDockerListResponse.result:type_name -> monitor.DockerListResult
	5,  // 11: monitor.GetDockerContainerDetailResponse.container:type_name -> monitor.DockerContainer
	7,  // 12: monitor.DockerContainer.PortBindingsEntry.value:type_name -> monitor.DockerPortBindings
	9,  // 13: monitor.AdminService.Register:input_type -> monitor.RegisterRequest
	11, // 14: monitor.AdminService.ReportError:input_type -> monitor.ErrorReport
	13, // 15: monitor.ServerService.HealthCheck:input_type -> monitor.HealthCheckRequest
	15, // 16: monitor.ServerService.GetSystemMetrics:input_type -> monitor.GetSystemMetricsRequest
	17, // 17: monitor.ServerService.GetSystemHistory:input_type -> monitor.GetSystemHistoryRequest
	19, // 18: monitor.ServerService.GetDockerMetrics:input_type -> monitor.GetDockerMetricsRequest
	21, // 19: monitor.ServerService.GetDockerList:input_type -> monitor.GetDockerListRequest
	23, // 20: monitor.ServerService.GetDockerContainerDetail:input_type -> monitor.GetDockerContainerDetailRequest
	10, // 21: monitor.AdminService.Register:output_type -> monitor.RegisterResponse
	12, // 22: monitor.AdminService.ReportError:output_type -> monitor.ErrorReportResponse
	14, // 23: monitor.ServerService.HealthCheck:output_type -> monitor.HealthCheckResponse
	16, // 24: monitor.ServerService.GetSystemMetrics:output_type -> monitor.GetSystemMetricsResponse
	18, // 25: monitor.ServerService.GetSystemHistory:output_type -> monitor.GetSystemHistoryResponse
	20, // 26: monitor.ServerService.GetDockerMetrics:output_type -> monitor.GetDockerMetricsResponse
	22, // 27: monitor.ServerService.GetDockerList:output_type -> monitor.GetDockerListResponse
	24, // 28: monitor.ServerService.GetDockerContainerDetail:output_type -> monitor.GetDockerContainerDetailResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_monitor_proto_init() }
func file_monitor_proto_init() {
	if File_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_proto_msgTypes,
	}.Build()
	File_monitor_proto = out.File
	file_monitor_proto_goTypes = nil
	file_monitor_proto_depIdxs = nil
}
